/**
 * Test Generator
 * Automated test generation from function signatures
 * 
 * Pattern: VALIDATION × TRUTH × CLARITY × ONE
 * Guardians: YAGNI × JØHN × AEYON
 */

import * as fs from 'fs'
import { parse } from '@typescript-eslint/typescript-estree'

interface TestCase {
  functionName: string
  testCases: string[]
}

export async function generateTests(filePath: string): Promise<string> {
  const content = fs.readFileSync(filePath, 'utf-8')
  const ast = parse(content, { loc: true, jsx: true })
  const tests: TestCase[] = []
  
  // Extract function signatures
  if (ast.body) {
    for (const node of ast.body) {
      if (node.type === 'FunctionDeclaration' || node.type === 'VariableDeclaration') {
        let funcName = ''
        let params: string[] = []
        
        if (node.type === 'FunctionDeclaration') {
          funcName = node.id?.name || 'anonymous'
          params = node.params.map(p => {
            if (p.type === 'Identifier') return p.name
            return 'param'
          })
        } else if (node.type === 'VariableDeclaration') {
          for (const decl of node.declarations) {
            if (decl.init && decl.init.type === 'ArrowFunctionExpression') {
              funcName = decl.id.type === 'Identifier' ? decl.id.name : 'anonymous'
              params = decl.init.params.map(p => {
                if (p.type === 'Identifier') return p.name
                return 'param'
              })
            }
          }
        }
        
        if (funcName && funcName !== 'anonymous') {
          const testCases = generateTestCases(funcName, params)
          tests.push({ functionName: funcName, testCases })
        }
      }
    }
  }
  
  return generateTestFile(tests)
}

function generateTestCases(funcName: string, params: string[]): string[] {
  const cases: string[] = []
  
  // Basic test case
  cases.push(`test('${funcName} should handle basic input', () => {`)
  cases.push(`  const result = ${funcName}(${params.map(() => 'testValue').join(', ')})`)
  cases.push(`  expect(result).toBeDefined()`)
  cases.push(`})`)
  cases.push('')
  
  // Null/undefined test
  cases.push(`test('${funcName} should handle null/undefined', () => {`)
  cases.push(`  expect(() => ${funcName}(${params.map(() => 'null').join(', ')})).not.toThrow()`)
  cases.push(`})`)
  cases.push('')
  
  // Edge case test
  cases.push(`test('${funcName} should handle edge cases', () => {`)
  cases.push(`  const result = ${funcName}(${params.map(() => '0').join(', ')})`)
  cases.push(`  expect(result).toBeDefined()`)
  cases.push(`})`)
  
  return cases
}

function generateTestFile(tests: TestCase[]): string {
  let output = `// Auto-generated test file\n`
  output += `// Generated by AI Validation Toolkit\n\n`
  output += `import { describe, test, expect } from '@jest/globals'\n\n`
  
  tests.forEach(({ functionName, testCases }) => {
    output += `describe('${functionName}', () => {\n`
    testCases.forEach(testCase => {
      output += `  ${testCase}\n`
    })
    output += `})\n\n`
  })
  
  return output
}

// CLI usage
if (require.main === module) {
  const filePath = process.argv[2] || 'src/function.ts'
  generateTests(filePath).then(testFile => {
    const outputPath = filePath.replace('.ts', '.test.ts')
    fs.writeFileSync(outputPath, testFile)
    console.log(`Test file generated: ${outputPath}`)
  })
}

